backend:
  name: git-gateway
  repo: slezakt/my-blog
  branch: main # Branch to update (optional; defaults to master)
  local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    widget: image
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "pages"
    label: "Pages"
    files:
      - label: "O mně"
        name: "omne"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: true,
            }
          - {
              label: "Content",
              name: "body",
              widget: "markdown",
              required: false,
            }
      - label: "Galerie"
        name: "galerie"
        file: "gallery/.md"
        fields:
          media_library:
            config:
              multiple: true
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Featured Image", name: "thumbnail", widget: "image" }